### ISSUE TITLE
When certain action is done, it doesn't automatically refresh to update

### ISSUE THREAD

**Issue by marksuriben** [xrockwell/sis#34]
UI ---> Refresh

**Comment by xrockwell** [comment]
<script src="https://gist.github.com/xrockwell/669420d5481cec5f9943.js"></script>

**Comment by xrockwell** [comment]
<script src="https://gist.github.com/xrockwell/669420d5481cec5f9943.js"></script>

**Comment by xrockwell** [comment]
https://gist.github.com/xrockwell/669420d5481cec5f9943

**Comment by xrockwell** [comment]
@marksuriben https://gist.github.com/xrockwell/669420d5481cec5f9943

**Comment by marksuriben** [comment]
@xrockwell  Done the reason is when you add new inquiry..  it reloads and redirect to the modules of new inquiry
